name: publish

on:
  pull_request: # TODO: remove this before merging, adding for testing purposes
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v1.0.0

      - name: Git Identity
        run: git config --global user.name '@tteltrab' && git config --global user.email 'tteltrab@users.noreply.github.com' && git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/$GITHUB_REPOSITORY
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Prepare repository
        run: git checkout "${GITHUB_REF:11}"

      - name: Pulling
        run: git pull

      - name: Install dependencies
        run: yarn

      - name: Publish with Lerna
        run: yarn lerna publish --yes --registry https://registry.npmjs.org/:_authToken=${NPM_TOKEN}
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
