name: publish

on:
  pull_request: # TODO: remove this before merging, adding for testing purposes
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@master
        with:
          ref: 'release/v1.0.0'

      - name: Install Packages
        run: yarn install

      - name: Test
        run: yarn test

      - name: Configure CI Git User
        run: |
          git remote rm origin
          git remote add origin "https://$USER_NAME:$GITHUB_PAT@github.com/IBM/slack-wrench.git"
          git fetch
          git config --global user.email octobot@github.com
          git config --global user.name GitHub Actions
        env:
          USER_NAME: ${{ secrets.DEPLOYING_USER_NAME }}
          GITHUB_PAT: ${{ secrets.GITHUB_PAT }}

      - name: Publish with Lerna
        run: yarn lerna publish --yes --registry https://registry.npmjs.org/:_authToken=${NPM_TOKEN}
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
