name: publish

on:
  pull_request: # TODO: remove this before merging, adding for testing purposes
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Read .nvmrc and pass it on
        run: echo ::set-output name=NVMRC::$(cat .nvmrc)
        id: nvm

      - name: Setup node w/ nvm version
        uses: actions/setup-node@v1
        with:
          node-version: '${{ steps.nvm.outputs.NVMRC }}'

      - name: Install Packages
        run: yarn install

      - name: Test
        run: yarn test

      - name: Publish package
        run: yarn publish-ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
